name: bible_app
description: A flutter project.
repository: https://github.com/Buried-In-Code/BibleApp
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/BBE/
    - assets/KJV/
    - assets/YLT/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/logo.png
  adaptive_icon_background: '#000000'
  adaptive_icon_foreground: assets/icons/logo.png
  remove_alpha_ios: true
